### ISSUE TITLE
ipaaca-cpp b3e26944 does not build on Ubuntu 16.04

### ISSUE THREAD

**Issue by hbuschme** [SocialCognitiveSystems/ipaaca#1]
IPAACA-cpp, starting commit b3e26944, does not build on Ubuntu 16.04, giving the following error message:

```
   [cmake] [ 65%] Linking CXX executable ipaaca-tester-cpp
   [cmake] CMakeFiles/ipaaca-tester-cpp.dir/build.make:417: recipe for target 'ipaaca-tester-cpp' failed
   [cmake] CMakeFiles/Makefile2:104: recipe for target 'CMakeFiles/ipaaca-tester-cpp.dir/all' failed
   [cmake] Makefile:127: recipe for target 'all' failed
   [cmake] /usr/bin/ld: CMakeFiles/ipaaca-tester-cpp.dir/src/ipaaca-buffers.cc.o: undefined reference to symbol 'pthread_mutexattr_settype@@GLIBC_2.2.5'
   [cmake] //lib/x86_64-linux-gnu/libpthread.so.0: error adding symbols: DSO missing from command line
   [cmake] collect2: error: ld returned 1 exit status
   [cmake] make[2]: *** [ipaaca-tester-cpp] Error 1
   [cmake] make[1]: *** [CMakeFiles/ipaaca-tester-cpp.dir/all] Error 2
   [cmake] make: *** [all] Error 2
```

**Comment by ryaghoub** [comment]
Fixed in c49795f2 by re-enabling the Linux(gcc)-specific flags
